### Obtener todos los superheroes
GET http://localhost:3000/api/heroes HTTP/1.1

### Obtener los datos de un superheroe usando su id 
GET http://localhost:3000/api/heroes/672387dc26845a4671452b32 HTTP/1.1

### Obtener una lista de superheroes que tengan un atributo especifico
GET http://localhost:3000/api/heroes/buscar/edad/26 HTTP/1.1